export const trainingActivityCardStyles = {
  root: "grid gap-4 rounded-xl border border-warning/50 bg-background p-4",
  completed: "border-info/60",
  paused: "border-muted-foreground/50",
  header: "grid gap-3",
  top: "flex items-start justify-between gap-3",
  title: "font-semibold text-foreground",
  headingToggle: "h-auto justify-start p-0 text-left whitespace-normal hover:bg-transparent",
  metadata: "text-xs text-muted-foreground",
  tools: "flex shrink-0 items-center gap-1",
  body: "grid gap-4",
  navigation: "flex items-center gap-2",
  session: "grid gap-3",
  sessionHeader: "flex items-start justify-between gap-3",
  sessionTitle: "font-semibold text-foreground",
  sessionMetadata: "text-sm text-muted-foreground",
  exercises: "grid gap-4",
  guidance: "text-sm text-muted-foreground",
} as const;
