export const trainingAgendaDrawerStyles = {
  trigger: "text-lg",
  content: "w-full max-w-md overflow-x-hidden overflow-y-auto",
  body: "grid min-w-0 gap-6 px-4 pb-6",
  section: "grid min-w-0 gap-3",
  title: "text-sm font-semibold text-foreground",
  description: "text-xs text-muted-foreground",
  item: "grid min-w-0 gap-3 rounded-lg border border-border bg-muted/20 p-3",
  itemHeading: "flex items-start justify-between gap-3",
  itemName: "font-medium text-foreground",
  itemMetadata: "text-xs text-muted-foreground",
  editor: "min-w-0 rounded-md border border-border px-3",
  editorSummary: "cursor-pointer py-3 text-sm font-medium text-muted-foreground",
  add: "min-w-0 rounded-lg border border-border px-3",
  addSummary: "cursor-pointer py-3 font-medium text-foreground",
} as const;
